# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-29 21:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventTitle', models.CharField(help_text='Event Name', max_length=50)),
                ('location', models.CharField(help_text='Location', max_length=100)),
                ('summary', models.TextField(help_text='Enter a brief description of the Event', max_length=1000)),
                ('picture', models.ImageField(upload_to='images/')),
                ('events', models.ManyToManyField(help_text='Events created by this user', to='gather.Event')),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter a name for the group', max_length=200)),
                ('description', models.TextField(help_text='Enter a bried description of the group', max_length=1000)),
                ('images', models.ImageField(upload_to='images/')),
                ('events', models.ManyToManyField(help_text='Add an event to this group', to='gather.Event')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='First Name', max_length=50)),
                ('last_name', models.CharField(help_text='Last Name', max_length=50)),
                ('picture', models.ImageField(default='images/user_pics/Default.jpg', upload_to='images/user_pics/')),
                ('events', models.ManyToManyField(help_text='Events created by this user', to='gather.Event')),
                ('friends', models.ManyToManyField(help_text='Friends of this user', to='gather.User')),
                ('groups', models.ManyToManyField(help_text='Groups this user is associated with', to='gather.Group')),
            ],
        ),
        migrations.AddField(
            model_name='group',
            name='members',
            field=models.ManyToManyField(help_text='Select members for this group', to='gather.User'),
        ),
        migrations.AddField(
            model_name='event',
            name='groups',
            field=models.ManyToManyField(help_text='Groups this user is associated with', to='gather.Group'),
        ),
        migrations.AddField(
            model_name='event',
            name='host',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gather.User'),
        ),
        migrations.AddField(
            model_name='event',
            name='invited',
            field=models.ManyToManyField(help_text='These users are invited to the event', related_name='invited', to='gather.User'),
        ),
        migrations.AddField(
            model_name='event',
            name='joined',
            field=models.ManyToManyField(help_text='Thse users have joined the Event', related_name='joined', to='gather.User'),
        ),
    ]
