# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-30 01:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gather', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='events',
        ),
        migrations.RemoveField(
            model_name='group',
            name='events',
        ),
        migrations.RemoveField(
            model_name='user',
            name='events',
        ),
        migrations.RemoveField(
            model_name='user',
            name='groups',
        ),
        migrations.AlterField(
            model_name='event',
            name='groups',
            field=models.ManyToManyField(help_text='Groups this user is associated with', related_name='events', to='gather.Group'),
        ),
        migrations.AlterField(
            model_name='event',
            name='host',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hosting', to='gather.User'),
        ),
        migrations.AlterField(
            model_name='group',
            name='members',
            field=models.ManyToManyField(help_text='Select members for this group', related_name='groups', to='gather.User'),
        ),
        migrations.AlterField(
            model_name='user',
            name='friends',
            field=models.ManyToManyField(help_text='Friends of this user', related_name='_user_friends_+', to='gather.User'),
        ),
    ]
