# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-30 01:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gather', '0002_auto_20171029_2152'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='eventTitle',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='event',
            name='host',
        ),
        migrations.AddField(
            model_name='event',
            name='hosts',
            field=models.ManyToManyField(help_text='These users are hosting the Event', related_name='hosting', to='gather.User'),
        ),
        migrations.AlterField(
            model_name='event',
            name='joined',
            field=models.ManyToManyField(help_text='These users have joined the Event', related_name='joined', to='gather.User'),
        ),
    ]
