# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-30 02:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gather', '0003_auto_20171029_2155'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='event',
            name='hosts',
        ),
        migrations.RemoveField(
            model_name='event',
            name='invited',
        ),
        migrations.RemoveField(
            model_name='event',
            name='joined',
        ),
        migrations.RemoveField(
            model_name='group',
            name='members',
        ),
        migrations.AddField(
            model_name='group',
            name='events',
            field=models.ManyToManyField(help_text='Select events for this group', related_name='groups', to='gather.Event'),
        ),
        migrations.AddField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(help_text='Select groups for this user', related_name='members', to='gather.Group'),
        ),
        migrations.AddField(
            model_name='user',
            name='hosting',
            field=models.ManyToManyField(help_text='Select events this user is hosting', related_name='hosts', to='gather.Event'),
        ),
        migrations.AddField(
            model_name='user',
            name='invited',
            field=models.ManyToManyField(help_text='Select events this user is invited to', related_name='invited', to='gather.Event'),
        ),
        migrations.AddField(
            model_name='user',
            name='joined',
            field=models.ManyToManyField(help_text='Select events this user has joined', related_name='joined', to='gather.Event'),
        ),
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.CharField(help_text='Enter a location for the event', max_length=100),
        ),
        migrations.AlterField(
            model_name='event',
            name='summary',
            field=models.TextField(help_text='Enter a brief description of the event', max_length=1000),
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(help_text='Enter a name for the event', max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(help_text="Enter user's first name", max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='friends',
            field=models.ManyToManyField(help_text='Select friends for this user', related_name='_user_friends_+', to='gather.User'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(help_text="Enter user's last name", max_length=50),
        ),
    ]
