# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-30 02:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gather', '0004_auto_20171029_2202'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='events',
        ),
        migrations.RemoveField(
            model_name='user',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='user',
            name='hosting',
        ),
        migrations.RemoveField(
            model_name='user',
            name='invited',
        ),
        migrations.RemoveField(
            model_name='user',
            name='joined',
        ),
        migrations.AddField(
            model_name='event',
            name='groups',
            field=models.ManyToManyField(help_text='Groups this user is associated with', related_name='events', to='gather.Group'),
        ),
        migrations.AddField(
            model_name='event',
            name='hosts',
            field=models.ManyToManyField(help_text='These users are hosting the Event', related_name='hosting', to='gather.User'),
        ),
        migrations.AddField(
            model_name='event',
            name='invited',
            field=models.ManyToManyField(help_text='These users are invited to the event', related_name='invited', to='gather.User'),
        ),
        migrations.AddField(
            model_name='event',
            name='joined',
            field=models.ManyToManyField(help_text='These users have joined the Event', related_name='joined', to='gather.User'),
        ),
        migrations.AddField(
            model_name='group',
            name='members',
            field=models.ManyToManyField(help_text='Select members for this group', related_name='groups', to='gather.User'),
        ),
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.CharField(help_text='Location', max_length=100),
        ),
        migrations.AlterField(
            model_name='event',
            name='summary',
            field=models.TextField(help_text='Enter a brief description of the Event', max_length=1000),
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(help_text='Event Name', max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(help_text='First Name', max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='friends',
            field=models.ManyToManyField(help_text='Friends of this user', related_name='_user_friends_+', to='gather.User'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(help_text='Last Name', max_length=50),
        ),
    ]
