# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-30 02:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gather', '0006_auto_20171029_2214'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='summary',
            new_name='description',
        ),
    ]
