# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-30 02:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gather', '0007_auto_20171029_2247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='images',
            field=models.ImageField(upload_to='static/images/'),
        ),
    ]
