# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-30 03:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gather', '0010_auto_20171029_2319'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='images',
            new_name='picture',
        ),
    ]
