# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-30 15:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gather', '0013_auto_20171030_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='Groups this user is associated with', related_name='events', to='gather.Group'),
        ),
        migrations.AlterField(
            model_name='event',
            name='invited',
            field=models.ManyToManyField(blank=True, help_text='These users are invited to the event', related_name='invited', to='gather.User'),
        ),
        migrations.AlterField(
            model_name='event',
            name='joined',
            field=models.ManyToManyField(blank=True, help_text='These users have joined the Event', related_name='joined', to='gather.User'),
        ),
        migrations.AlterField(
            model_name='user',
            name='friends',
            field=models.ManyToManyField(blank=True, help_text='Friends of this user', related_name='_user_friends_+', to='gather.User'),
        ),
    ]
