# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-07 21:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gather', '0016_auto_20171107_1505'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='First Name', max_length=50)),
                ('last_name', models.CharField(help_text='Last Name', max_length=50)),
                ('picture', models.ImageField(default='images/user/placeholder.png', upload_to='images/user/')),
                ('friends', models.ManyToManyField(blank=True, help_text='Friends of this user', related_name='_profile_friends_+', to='gather.Profile')),
            ],
            options={
                'ordering': ['last_name'],
            },
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='friends',
        ),
        migrations.AlterField(
            model_name='event',
            name='hosts',
            field=models.ManyToManyField(help_text='These users are hosting the Event', related_name='hosting', to='gather.Profile'),
        ),
        migrations.AlterField(
            model_name='event',
            name='invited',
            field=models.ManyToManyField(blank=True, help_text='These users are invited to the event', related_name='invited', to='gather.Profile'),
        ),
        migrations.AlterField(
            model_name='event',
            name='joined',
            field=models.ManyToManyField(blank=True, help_text='These users have joined the Event', related_name='joined', to='gather.Profile'),
        ),
        migrations.AlterField(
            model_name='groupprofile',
            name='members',
            field=models.ManyToManyField(help_text='Select members for this group', related_name='groups', to='gather.Profile'),
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
