# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-07 21:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gather', '0017_auto_20171107_1650'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GroupProfile',
            new_name='EventGroup',
        ),
    ]
